---
apiVersion: v1
kind: Secret
metadata:
  name: backend-redis
stringData:
  REDIS_STORAGE_URL: "redis://user:pass@redis:6379/0"
  REDIS_QUEUES_URL: "redis://user:pass@redis:6379/1"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: system-database
stringData:
  URL: "postgresql://user:pass@pgsql:5432/system"
  DB_USER: "postgresql"
  DB_PASSWORD: "password"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: system-redis
stringData:
  URL: "redis://user:pass@redis:6379/2"
  MESSAGE_BUS_URL: "redis://user:pass@redis:6379/8"
type: Opaque
